### ISSUE TITLE
windowless windows

### ISSUE THREAD

**Issue by Jesseman1** [quarantin/zomboid-off-the-window#15]
After your recent patch I was given an option to throw corpses out of window frames, but they don't actually go out the window.
![Throw them out the window](https://user-images.githubusercontent.com/26986519/151751291-10ff68f7-0146-49bd-911d-3bfed2deb586.jpg)
In this picture I have tried to throw about 5 corpses out the hole, but they get moved to this spot my character is looking at instead.

**Comment by quarantin** [comment]
Can you send me a map link so that I can try it myself? I can't reproduce the issue on my side.

**Comment by Jesseman1** [comment]
How do I give a map link? This is the second floor of the Rosewood firestation.

**Comment by quarantin** [comment]
About the map link I was thinking about https://map.projectzomboid.com/ but second floor of the Rosewood firestation is also OK. But in the meantime I realized my patch only works for window frames when they are on the West/East axis. Problem is this is really an issue with the game engine. I will try to find a way around that problem but no guarantee :/
Thanks for the feedback!

**Comment by Luckynoobik** [comment]
Hello. Got one error when throwing the body out the window. https://pastebin.com/N00BUXEb

**Comment by quarantin** [comment]
Hi, could you send the whole stack trace please? I need it to understand the issue

**Comment by Luckynoobik** [comment]
Yes, of course, sorry, I should have done it right away.
https://drive.google.com/file/d/1v95eEnpnsl-ibTCuEWsiAtyV7G_I0Ms_/view?usp=sharing
If you look in the notepad++, then the error was in line 67715.

**Comment by quarantin** [comment]
Hum strange, can you give more details about what triggered this? Was it while trying to throw a corpse through a window frame with not window? Also the coordinates on the map (https://map.projectzomboid.com/) where you got the issue could help.

**Comment by Luckynoobik** [comment]
The window was broken, but the body was thrown out of the window anyway. It seems to be in this house, in the lower right room. If I can reproduce this error again, I will try to record it on video.
https://map.projectzomboid.com/#0.29646054507344216,0.24621997697466289,817.0886597938145

**Comment by Luckynoobik** [comment]
One more question, if I may. Having approached the closed window with the body, it can still be thrown out. Is it supposed to be like this? In this case, the body is thrown out the window as it should, without any error.

**Comment by quarantin** [comment]
oh wow, this is even more weird than I thought, the crash suggest the mod was not able to find the square where it should drop the corpse. So theoretically there's no way it was able to drop the corpse. I'll still try to see if I can reproduce the issue

**Comment by quarantin** [comment]
hum no it should not be able to throw a corpse through a closed window, however close you are from the window. I remember seeing weird map bugs where there was multiple window frames on the same square. Guess that could explain this. I can have a look if you also share the coordinates for where this happened.

**Comment by Luckynoobik** [comment]
I specifically disabled all mods, leaving only yours. Here's a video. I can throw the body out of the window, with the window closed.
https://www.youtube.com/watch?v=MxiW2Omtz30
It was in this house. On the first floor. And I'm afraid that this is the case in any house.
https://map.projectzomboid.com/#0.2811947403821814,0.2424274084384293,817.0886597938145
And I apologize for my English

**Comment by quarantin** [comment]
FYI I Just fixed the bug allowing to throw corpse out of closed/barricaded windows. Thank you for reporting it!

**Comment by Luckynoobik** [comment]
Thanks for letting me know and thanks for fixing this.
