### ISSUE TITLE
Doesn't work with old saves

### ISSUE THREAD

**Issue by Lohkan143** [quarantin/zomboid-off-the-window#25]
Hello! I found it doesn't work with old saves, it works with new saves though. I don't believe it's conflicting with other mods because it works perfectly in new saves.

Some pictures for reference! I hope they help!

New Save:
![NewSave](https://user-images.githubusercontent.com/131225277/232956216-e43b9e4f-5f2b-4e3a-9c56-413d477d8403.png)

Old Save:
![OldSave](https://user-images.githubusercontent.com/131225277/232955476-8614339b-fc47-4368-92ed-c88029d529cf.png)

**Comment by quarantin** [comment]
I really doubt using old version of the game has anything to do with the mod working or not. I rather suspect your saved game does not have the mod enabled. Can you share a screenshot of when you load the saved game so I can see what mods are enabled or not?

**Comment by Lohkan143** [comment]
> I really doubt using old version of the game has anything to do with the mod working or not. I rather suspect your saved game does not have the mod enabled. Can you share a screenshot of when you load the saved game so I can see what mods are enabled or not?

You are correct, I hadn't played in a few months so forgot I need to enable the mod for old saves. Thank you for your help an mod, I apologize for taking up your time an hope if I find an actual bug I can be of help!
