### ISSUE TITLE
Version for Build 42

### ISSUE THREAD

**Issue by vico93** [quarantin/zomboid-off-the-window#30]
Since Indie Stone didnt bother to add window-throwing alongside the new corpse-dragging feature, i wonder if an update to this much-needed feature is on the plans for b42...

**Comment by quarantin** [comment]
Hello @vico93,

As far I know, throwing corpses out of windows is part of b42.

**Comment by vico93** [comment]
> Hello @vico93,
> 
> As far I know, throwing corpses out of windows is part of b42.

Really? tried here and wasnt able to do it.

I think i will try again next time. thanks for the information!
